controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

reverse_geocode:
    path: /reverse-geocode
    controller: App\Controller\GeocodeController::reverseGeocode