app_sortie_index:
    path: /
    controller: 'App\Controller\SortieController::index'
    methods: ['GET']

app_sortie_show:
    path: '/sortie/{id}'
    controller: 'App\Controller\SortieController::show'
    methods: ['GET']

app_sortie_edit:
    path: '/sortie/{id}/edit'
    controller: 'App\Controller\SortieController::edit'
    methods: ['GET', 'POST']

app_sortie_new:
    path: '/sortie/new'
    controller: 'App\Controller\SortieController::new'
    methods: ['GET', 'POST']

app_login:
    path: '/login'
    controller: 'App\Controller\SecurityController::login'
    methods: [ 'GET', 'POST' ]

app_logout:
    path: '/logout'
    controller: 'App\Controller\SecurityController::logout'
    methods: [ 'GET', 'POST' ]

app_participant_index:
    path: '/participant'
    controller: 'App\Controller\ParticipantController::index'
    methods: ['GET']

app_participant_show:
    path : '/participant/{id}'
    controller: 'App\Controller\ParticipantController::show'
    methods: ['GET']

app_participant_edit:
    path : '/participant/{id}/edit'
    controller: 'App\Controller\ParticipantController::edit'
    methods: ['GET', 'POST']

app_participant_new:
    path : '/participant/new'
    controller: 'App\Controller\ParticipantController::new'
    methods: ['GET', 'POST']

app_participant_delete:
    path: '/participant/{id}'
    controller: 'App\Controller\ParticipantController::delete'
    methods: ['POST']